name: Update days
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Update README.md
        id: update_readme
        run: |
          date_start=${{secrets.LEAVE_DATE}}
          last_modify_time_badge_content=`date +"%Y--%m--%d_%H:%M:%S"`
          date_end=`date +"%Y-%m-%d"`
          date_start_second=`date -d"$date_start" +"%s"`
          date_end_second=`date -d"$date_end" +"%s"`
          interval=$[$date_end_second-$date_start_second]
          interval_days=$[$interval/86400]
          echo "::set-output name=interval_days::$interval_days"
          sed -i -r "s#leave-[0-9]+_days#leave-${interval_days}_days#g" README.md
          sed -i -r "s#last--modify-[0-9]{4}--[0-9]{1,2}--[0-9]{1,2}_([0-9]{2}:){2}[0-9]{2}#last--modify-${last_modify_time_badge_content}#g" README.md
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: "Update ${{ steps.update_readme.outputs.interval_days }} days"
